### ISSUE TITLE
The Transaction ID it return's isn't true

### ISSUE THREAD

**Issue by elichai** [laanwj/bitcoin-submittx#1]
It returns a false transaction ID at the end

**Comment by laanwj** [comment]
Strange! Can you give an example?

**Comment by elichai** [comment]
https://gist.github.com/elichai/ae716137579f3f705dd2441da2b93754
the txid in the output was this: `721e4bc5a070edf2bac39456b4aa31c8851850a92cf5a33572add40795187e60`

and here is the actual txid is: https://blockchain.info/tx/2cc20585f6e31f1ea56b150e2e163ecde0a9d0b7a4d26a840aac5ef8db0b2092

**Comment by laanwj** [comment]
You're right, the transaction ID is indeed computed wrongly! Thanks a lot for reporting this, should be fixed now.
